service: api-python-hello

provider:
  name: aws
  region: us-east-1
  runtime: python3.7
  stage: dev
functions:
  hello:
    handler: src/item.hello_world
    runtime: python3.7
    memorySize: 256
    timeout: 20
    events:
      - http:
          path: api/python/hello
          method: get
          integration: lambda  